trigger:
  branches:
    include:
      - feature/packer


pool:
  vmImage: 'ubuntu-latest'

stages:
  - template: ./build.yaml
    parameters:
      library: 'dev'
      deploymentEnvironmentName: dev
      stage_name: BuildDev
      subscription_endpoint: 'Visual Studio Enterprise Subscription'
 